name: Build

on:
  pull_request:
    branches:
      - 'master'

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Setup
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      # Fix annoying packages not being found
      - name: Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      # .NET
      - name: Restore .NET packages
        run: dotnet restore

      - name: Build .NET projects
        run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}

      - name: Test .NET projects
        run: dotnet test --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }}
