name: Deploy

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/README.md'

env:
  BUILD_CONFIGURATION: Release
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # Setup
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      # Fix annoying packages not being found
      - name: Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      # .NET
      - name: Restore .NET packages
        run: dotnet restore

      - name: Build .NET projects
        run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}

      - name: 'Pack Core project'
        run: dotnet pack Endpointer.Core --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }} --include-symbols --include-source --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Pack Core API project'
        run: dotnet pack Endpointer.Core.API --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }} --include-symbols --include-source --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Pack Core Client project'
        run: dotnet pack Endpointer.Core.Client --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }} --include-symbols --include-source --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Pack Authentication Core project'
        run: dotnet pack Endpointer.Authentication.Core --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }} --include-symbols --include-source --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Pack Authentication API project'
        run: dotnet pack Endpointer.Authentication.API --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }} --include-symbols --include-source --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Pack Authentication Client project'
        run: dotnet pack Endpointer.Authentication.Client --no-restore --no-build -c ${{ env.BUILD_CONFIGURATION }} --include-symbols --include-source --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push packages'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
